services:
  postgres-cliente:
    image: postgres:16-alpine
    container_name: devsu-postgres-cliente
    environment:
      POSTGRES_DB: cliente_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5433:5432"
    volumes:
      - pgdata-cliente:/var/lib/postgresql/data
      - ./docker/postgres-cliente/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d cliente_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-cuenta:
    image: postgres:16-alpine
    container_name: devsu-postgres-cuenta
    environment:
      POSTGRES_DB: cuenta_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5434:5432"
    volumes:
      - pgdata-cuenta:/var/lib/postgresql/data
      - ./docker/postgres-cuenta/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d cuenta_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: devsu-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  cliente-service:
    build:
      context: .
      dockerfile: cliente-service/Dockerfile
    container_name: devsu-cliente-service
    depends_on:
      postgres-cliente:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-cliente:5432/cliente_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    ports:
      - "8081:8081"

  cuenta-service:
    build:
      context: .
      dockerfile: cuenta-service/Dockerfile
    container_name: devsu-cuenta-service
    depends_on:
      postgres-cuenta:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      cliente-service:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-cuenta:5432/cuenta_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    ports:
      - "8082:8082"

volumes:
  pgdata-cliente:
  pgdata-cuenta:
